#!/bin/sh

profile=

# If you run 'aptest profile' you will get a dump of all functions to ap-profile.log
if [ "$1" = profile ]; then
  profile="-p ap-profile.log"
fi

echo "----------- `date` -------------------" >> aptest.log
PYTHONPATH="`pwd`" twistd2.3 $profile -n -y bin/apt-proxy | tee -a aptest.log
