#!/bin/sh

#DEBHELPER#

NAME=apt-proxy-v2

if test "$1" = "purge"; then
  rm -rf /var/log/$NAME.log
  echo Purging apt-proxy cache directory
  rm -rf /var/cache/$NAME

  # Don't do this until ap1 is no longer used
  #if id aptproxy >/dev/null; then
  #  deluser aptproxy
  #fi
fi

