#!/bin/sh

#DEBHELPER#

if test "$1" = "purge"; then
  echo y|update-inetd --remove 9999 2>&1 > /dev/null
  rm -rf /var/log/apt-proxy.log
  echo Purging apt-proxy cache directory
  rm -rf /var/cache/apt-proxy
  if id aptproxy >/dev/null; then
    deluser aptproxy
  fi
fi

