#!/bin/sh

#DEBHELPER#

NAME=apt-proxy-v2
CACHEDIR=/var/cache/apt-proxy

if test "$1" = "purge"; then
  rm -rf /var/log/$NAME.log

  # Don't do this until ap1 is no longer used
  #echo Purging apt-proxy cache directory
  #rm -rf $CACHEDIR

  #if id aptproxy >/dev/null; then
  #  deluser aptproxy
  #fi
fi

