#! /bin/sh

#DEBHELPER#

PYVER=2.2
NAME=apt-proxy-v2
APTPROXY_USER=aptproxy
APTPROXY_LOGFILE=/var/log/$NAME.log
CACHEDIR=/var/cache/apt-proxy

set -e
case "$1" in
    configure)
	# First time installation only.  Upgrades skip this.
	if [ "$2" = "" ]; then

	    # Create user
	    if [ -x /usr/sbin/adduser ]; then
	        echo creating $APTPROXY_USER user...
	        id $APTPROXY_USER > /dev/null 2>&1 ||
		    adduser --quiet --system --ingroup nogroup \
		    --home $CACHEDIR --no-create-home $APTPROXY_USER
	    fi

	    # Make apt-proxy user own cache directory
	    chown -R $APTPROXY_USER $CACHEDIR
	    # Create a blank logfile owned by apt-proxy user
	    touch $APTPROXY_LOGFILE
	    chown $APTPROXY_USER:adm $APTPROXY_LOGFILE
	    chmod 640 $APTPROXY_LOGFILE
	fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        ;;
esac

# Compile python
case "$1" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)
        dpkg --listfiles $NAME | grep '\.py$' | \
	     xargs -n 1 /usr/bin/python$PYVER -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
	dpkg --listfiles $NAME | grep '\.py$' | \
	     xargs -n 1 /usr/bin/python$PYVER -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
    ;;
esac

exit 0
