#! /bin/sh

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

if [ -e /etc/apt-proxy/apt-proxy-v2.conf ]; then
	db_fset apt-proxy/upgrading-v2 had_v2_conf true
else
	db_fset apt-proxy/upgrading-v2 had_v2_conf false
fi

db_stop
